baseURL = '/'
languageCode = 'en-us'
title = 'zesty sauce'
theme = 'photophobia'
enableGitInfo = true
frontmatter:
date:
- date
- publishDate
- lastmod
expiryDate:
- expiryDate
lastmod:
- :git
- lastmod
- date
- publishDate
publishDate:
- publishDate
- date
